name: CI
on: [push, pull_request]

jobs:
  Build:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2
    - uses: microsoft/setup-msbuild@v1.0.2
    - name: Restore packages
      run: msbuild src/LudusaviPlaynite.csproj /t:restore
    - name: Build
      run: msbuild src/LudusaviPlaynite.csproj /t:build
